"use strict";

const GAS_URL="https://script.google.com/macros/s/AKfycbzS1F43nO_ZDG6X6gH4qfUeprWmFFOZuthQKjbXxuxkoTWY0QMvbAfURd2speGZEa6x/exec";
const loadingMessage=document.getElementById("status-loading");
let statusData={}; let notices=[]; let selectedNotice=null;
const text=(v,f="―")=>v===null||v===undefined||v===""?f:String(v);
const pick=(obj,keys,f="")=>{for(const k of keys){if(obj&&obj[k]!==undefined&&obj[k]!==null&&obj[k]!=="")return obj[k]}return f};

function setBasicInfo(info={}){document.getElementById("basic-name").textContent=text(info.name||info["薬局・店舗販売業の名称"]);document.getElementById("basic-owner").textContent=text(info.owner||info["開設者氏名(又は代表者)"]);document.getElementById("basic-manager").textContent=text(info.manager||info["管理者氏名"]);document.getElementById("basic-address").textContent=text(info.address||info["所在地"]);document.getElementById("basic-hours").textContent=text(info.openingHours||info["開局時間"])}
function statusClass(item){if(item.status==="expired"||item.status==="red")return"red";if(item.status==="soon"||item.status==="orange")return"orange";if(item.status==="valid"||item.status==="green")return"green";return"gray"}
function statusLabel(item){if(item.statusLabel)return item.statusLabel;return{red:"期限切れ",orange:"3ヶ月以内",green:"有効",gray:"期限未設定"}[statusClass(item)]}
function makeRow(item,deadline=false){const row=document.createElement("div"),kind=statusClass(item);row.className=`list-row${deadline?` deadline-row ${kind}`:""}`;const main=document.createElement("div");main.className="list-main";const title=document.createElement("span");title.className="list-title";title.textContent=text(item.title||item.type||item.name||item.種類,"名称未設定");main.appendChild(title);const details=[item.number||item.licenseNumber||item.許可番号,item.deadline||item.expiration||item.有効期限,item.remaining].filter(Boolean);if(details.length){const d=document.createElement("span");d.className="list-detail";d.textContent=details.join(" ／ ");main.appendChild(d)}const badge=document.createElement("span");badge.className=`badge ${kind}`;badge.textContent=statusLabel(item);row.append(main,badge);return row}
function renderList(id,items,options={}){const c=document.getElementById(id);c.textContent="";if(!items||!items.length){const e=document.createElement("p");e.className="empty-message";e.textContent=options.empty||"登録データはありません。";c.appendChild(e);return}items.slice(0,options.limit||items.length).forEach(i=>c.appendChild(makeRow(i,options.deadline)))}
function setAllLink(id,url){const a=document.getElementById(id);if(!url)return;a.href=url;a.target="_blank";a.rel="noopener noreferrer";a.hidden=false}
function renderNames(id,items,emptyText){const c=document.getElementById(id);c.textContent="";if(!items||!items.length){const e=document.createElement("p");e.className="empty-message";e.textContent=emptyText;c.appendChild(e);return}items.forEach(n=>{const chip=document.createElement("div");chip.className="name-chip";if(typeof n==="string"){chip.textContent=n;c.appendChild(chip);return}const nameText=text(n.name||n["薬剤師　氏名"]||n["登録販売者　氏名"]||n.氏名,"氏名未設定");const licenseNumber=pick(n,["薬剤師登録番号","登録番号"],"");const insuranceNumber=pick(n,["保険薬剤師登録番号"],"");const registeredDate=n["登録年月日"];const title=document.createElement("span");title.className="list-title";title.textContent=nameText;chip.appendChild(title);const details=[];if(licenseNumber)details.push(`薬剤師登録番号：${licenseNumber}`);if(insuranceNumber)details.push(`保険薬剤師登録番号：${insuranceNumber}`);if(registeredDate)details.push(`登録年月日：${formatDate(registeredDate)}`);if(details.length){const d=document.createElement("span");d.className="list-detail";d.textContent=details.join(" ／ ");chip.appendChild(d)}c.appendChild(chip)})}

function normalizeNotice(raw,index){const type=pick(raw,["name","届出種別","title","type","種類"],"名称未設定");const condition=pick(raw,["deadlineCondition","有効期限・更新条件","有効期限","deadline","expiration"],"");const dateRaw=pick(raw,["specifiedDate","指定年月日","date"],"");const date=typeof dateRaw==="object"&&dateRaw!==null?(dateRaw.start||""):dateRaw;const number=pick(raw,["numberNote","指定番号・備考","指定番号","number","licenseNumber"],"");const order=Number(pick(raw,["並び順","order"],index+1))||index+1;const id=pick(raw,["id","pageId"],"");return{...raw,id,type,condition,date,number,order,state:noticeState({raw,type,condition,date,number})}}
function noticeState(x){const acquisition=String(pick(x.raw,["取得状況"],"")).trim();if(acquisition&&acquisition!=="取得済み")return"none";const explicit=String(pick(x.raw,["status","statusLabel"],"")).toLowerCase();if(explicit.includes("expired")||explicit.includes("期限切"))return"expired";if(explicit.includes("soon")||explicit.includes("orange")||explicit.includes("3ヶ月"))return"soon";if(explicit.includes("valid")||explicit.includes("green")||explicit.includes("有効"))return"valid";const all=`${x.condition} ${x.number}`;if(/届出なし|未届|届出していない/.test(all))return"none";if(x.date||x.number)return"valid";return"check"}
function stateLabel(s){return{valid:"有効",soon:"更新が近い",expired:"期限切れ",none:"届出なし",check:"要確認"}[s]||"要確認"}
function stateBadgeClass(s){return{valid:"green",soon:"orange",expired:"red",none:"none",check:"gray"}[s]||"gray"}
function formatDate(v){if(!v)return"—";if(typeof v==="object"&&v!==null)v=v.start||"";if(!v)return"—";const s=String(v).slice(0,10);return/^\d{4}-\d{2}-\d{2}$/.test(s)?s.replaceAll("-","/"):s}
function renderNotices(){const q=document.getElementById("notice-search").value.trim().toLowerCase(),filter=document.getElementById("notice-filter").value;const list=notices.filter(n=>(!q||n.type.toLowerCase().includes(q))&&(filter==="all"||n.state===filter));const c=document.getElementById("notice-list");c.textContent="";if(!list.length){c.innerHTML='<p class="empty-message">条件に一致する届出はありません。</p>';return}list.forEach(n=>{const b=document.createElement("button");b.type="button";b.className=`notice-row${n.state==="none"?" notice-none":""}`;b.innerHTML=`<span class="notice-order">${n.order}</span><span><span class="notice-title"></span><span class="notice-mobile-meta"></span></span><span class="notice-condition"></span><span class="notice-date"></span><span class="badge ${stateBadgeClass(n.state)}">${stateLabel(n.state)}</span><span class="notice-arrow">›</span>`;b.querySelector(".notice-title").textContent=n.type;b.querySelector(".notice-condition").textContent=text(n.condition);b.querySelector(".notice-date").textContent=formatDate(n.date);b.querySelector(".notice-mobile-meta").textContent=[n.condition,formatDate(n.date)].filter(v=>v&&v!=="―").join(" ／ ");b.addEventListener("click",()=>openDetail(n));c.appendChild(b)})}
function renderNoticeSummary(){const counts={valid:0,soon:0,expired:0,none:0,check:0};notices.forEach(n=>counts[n.state]=(counts[n.state]||0)+1);document.getElementById("notice-total").textContent=notices.length;document.getElementById("notice-valid").textContent=counts.valid;document.getElementById("notice-soon").textContent=counts.soon;document.getElementById("notice-expired").textContent=counts.expired;document.getElementById("notice-none").textContent=counts.none}

function openDetail(n){selectedNotice=n;const box=document.getElementById("notice-detail-view");box.hidden=false;document.getElementById("notice-form").hidden=true;document.getElementById("notice-modal-title").textContent="届出の詳細";box.innerHTML="";const title=document.createElement("div");title.className="detail-title-row";title.innerHTML=`<h3></h3><span class="badge ${stateBadgeClass(n.state)}">${stateLabel(n.state)}</span>`;title.querySelector("h3").textContent=`#${n.order}　${n.type}`;box.appendChild(title);const dl=document.createElement("dl");dl.className="detail-grid";[["有効期限・更新条件",n.condition],["指定年月日",formatDate(n.date)],["指定番号・備考",n.number],["並び順",n.order],["更新日",pick(n,["updatedAt","更新日","last_edited_time"],"―")],["作成日",pick(n,["createdAt","作成日","created_time"],"―")]].forEach(([k,v])=>{const d=document.createElement("div");d.className="detail-field";d.innerHTML="<dt></dt><dd></dd>";d.querySelector("dt").textContent=k;d.querySelector("dd").textContent=text(v);dl.appendChild(d)});box.appendChild(dl);const actions=document.createElement("div");actions.className="detail-actions";actions.innerHTML='<button class="primary-button" type="button">編集する</button><button class="danger-button" type="button">削除する</button>';actions.children[0].onclick=()=>openEdit(n);actions.children[1].onclick=()=>openDelete(n);box.appendChild(actions);showModal("notice-modal")}
function openEdit(n){selectedNotice=n;document.getElementById("notice-detail-view").hidden=true;const f=document.getElementById("notice-form");f.hidden=false;document.getElementById("notice-modal-title").textContent=n?"届出を編集":"新規届出を追加";document.getElementById("notice-id").value=n?.id||"";document.getElementById("notice-type").value=n?.type||"";document.getElementById("notice-deadline").value=n?.condition||"";document.getElementById("notice-date").value=n?.date?String(n.date).slice(0,10):"";document.getElementById("notice-number").value=n?.number||"";document.getElementById("notice-order").value=n?.order||((notices.at(-1)?.order||0)+1);showModal("notice-modal")}
function openDelete(n){selectedNotice=n;document.getElementById("delete-target-name").textContent=`${n.type}（並び順：${n.order}）`;showModal("delete-modal")}
function showModal(id){document.getElementById(id).hidden=false;document.body.style.overflow="hidden"}function hideModal(id){document.getElementById(id).hidden=true;if(document.getElementById("notice-modal").hidden&&document.getElementById("delete-modal").hidden)document.body.style.overflow=""}
async function apiWrite(action,payload){const r=await fetch(GAS_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})});const j=await r.json();if(!j.success)throw new Error(j.message||"保存に失敗しました。");return j}

function renderStatus(data){statusData=data;setBasicInfo(data.basicInfo);renderList("deadline-alerts",data.alerts,{deadline:true,empty:"3ヶ月以内の更新期限はありません。"});renderList("license-list",data.licenses,{limit:6,empty:"許可・登録データはありません。"});notices=(data.notices||[]).map(normalizeNotice).sort((a,b)=>a.order-b.order);renderNoticeSummary();renderNotices();setAllLink("license-all-link",data.licenseDatabaseUrl);setAllLink("notice-all-link",data.noticeDatabaseUrl);const survey=data.prescriptionSurvey||{},completed=Number(survey.completed||0),total=Number(survey.total||13);document.getElementById("survey-count").textContent=`${completed}/${total}`;const sb=document.getElementById("survey-label");sb.textContent=completed>=total?"入力済み":`${total-completed}件 未入力`;sb.className=`badge ${completed>=total?"green":"orange"}`;const pharmacists=(data.pharmacists||[]).slice().sort((a,b)=>{const orderA=typeof a==="object"?Number(a["並び順"]):NaN;const orderB=typeof b==="object"?Number(b["並び順"]):NaN;const hasA=!isNaN(orderA),hasB=!isNaN(orderB);if(hasA&&hasB)return orderA-orderB;if(hasA)return -1;if(hasB)return 1;return 0});renderNames("pharmacist-list",pharmacists,"薬剤師の登録はありません。");renderNames("seller-list",data.registeredSellers,"在籍なし")}
async function loadStatus(){loadingMessage.className="loading-message";loadingMessage.textContent="データを読み込んでいます…";try{const response=await fetch(`${GAS_URL}?action=status&_=${Date.now()}`),result=await response.json();if(!result.success)throw new Error(result.message||"読み込みに失敗しました。");renderStatus(result.data||result);loadingMessage.textContent=""}catch(e){loadingMessage.className="loading-message error";loadingMessage.textContent="現在、データを読み込めません。GAS連携を確認してください。"}}

document.getElementById("reload-button").addEventListener("click",loadStatus);document.getElementById("notice-search").addEventListener("input",renderNotices);document.getElementById("notice-filter").addEventListener("change",renderNotices);document.getElementById("add-notice-button").addEventListener("click",()=>openEdit(null));document.querySelectorAll("[data-close-modal]").forEach(x=>x.addEventListener("click",()=>hideModal("notice-modal")));document.querySelectorAll("[data-close-delete]").forEach(x=>x.addEventListener("click",()=>hideModal("delete-modal")));document.querySelectorAll(".status-tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".status-tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.getElementById(t.dataset.target)?.scrollIntoView({behavior:"smooth",block:"start"})}));
document.getElementById("notice-form").addEventListener("submit",async e=>{e.preventDefault();const payload={id:document.getElementById("notice-id").value,notice:{"届出種別":document.getElementById("notice-type").value.trim(),"有効期限・更新条件":document.getElementById("notice-deadline").value.trim(),"指定年月日":document.getElementById("notice-date").value,"指定番号・備考":document.getElementById("notice-number").value.trim(),"並び順":Number(document.getElementById("notice-order").value)}};try{loadingMessage.textContent="保存しています…";await apiWrite("saveStatusNotice",payload);hideModal("notice-modal");await loadStatus()}catch(err){loadingMessage.className="loading-message error";loadingMessage.textContent=`保存できません：${err.message}（GAS側の書き込みAPI追加後に有効になります）`}});
document.getElementById("confirm-delete").addEventListener("click",async()=>{if(!selectedNotice)return;try{loadingMessage.textContent="削除しています…";await apiWrite("deleteStatusNotice",{id:selectedNotice.id});hideModal("delete-modal");hideModal("notice-modal");await loadStatus()}catch(err){loadingMessage.className="loading-message error";loadingMessage.textContent=`削除できません：${err.message}（GAS側の書き込みAPI追加後に有効になります）`}});
loadStatus();
